import { useEffect, useState } from 'react';

type Claim = { id: string; make: string; model: string; variant: string | null; component: string; issue: string; symptoms: string[]; repair: string | null; evidence_level: string; confidence: number; language: string; source_count: number };
type Job = { id: string; make: string; model: string; status: string; error: string | null };
const api = 'http://localhost:8787/api';
type VehicleForm = { make: string; model: string; generation: string; variant: string; engine: string; engineCode: string; transmission: string };
const emptyVehicle: VehicleForm = { make: '', model: '', generation: '', variant: '', engine: '', engineCode: '', transmission: '' };

function ResearchDebug() {
  const [claims, setClaims] = useState<Claim[]>([]); const [jobs, setJobs] = useState<Job[]>([]); const [error, setError] = useState(''); const [url, setUrl] = useState(''); const [vehicle, setVehicle] = useState<VehicleForm>(emptyVehicle); const [activeVehicle, setActiveVehicle] = useState<VehicleForm | null>(null); const [inspectMessage, setInspectMessage] = useState('');
  const reload = (filter?: VehicleForm | null) => { const query = filter ? `?${new URLSearchParams(Object.entries({ make: filter.make, model: filter.model, variant: filter.variant, engine: filter.engine }).filter(([, value]) => Boolean(value)) as string[][]).toString()}` : ''; return Promise.all([fetch(`${api}/claims${query}`).then((r) => r.json()), fetch(`${api}/jobs`).then((r) => r.json())]).then(([claimData, jobData]) => { setClaims(Array.isArray(claimData) ? claimData : []); setJobs(Array.isArray(jobData) ? jobData : []); }); };
  useEffect(() => { fetch(`${api}/jobs`).then((r) => r.json()).then((jobData) => { if (Array.isArray(jobData)) setJobs(jobData); }).catch((reason: unknown) => setError(reason instanceof Error ? reason.message : 'Research API ei ole käivitatud')); }, []);
  const inspect = async () => { setInspectMessage('Loen Auto24 linki…'); try { const result = await fetch(`${api}/auto24/inspect`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ url }) }).then((r) => r.json()); if (result.vehicle) setVehicle({ ...emptyVehicle, ...Object.fromEntries(Object.entries(result.vehicle).map(([key, value]) => [key === 'engineCode' ? 'engineCode' : key, value ?? ''])) }); setInspectMessage(result.message ?? 'Andmed tuvastatud — kontrolli need üle.'); } catch { setInspectMessage('Auto24 linki ei saanud lugeda. Täida andmed käsitsi.'); } };
  const queue = async () => { const result = await fetch(`${api}/research-jobs`, { method: 'POST', headers: { 'content-type': 'application/json' }, body: JSON.stringify({ vehicle, priority: 10 }) }).then((r) => r.json()); if (result.error) setInspectMessage(result.error); else { setActiveVehicle(vehicle); setInspectMessage(`Auto lisati research-järjekorda: ${result.id}`); await reload(vehicle); } };
  return <main className="page"><div className="container"><h1>Research-agenti ülevaade</h1><p>Lokaalne vaade PostgreSQL-i salvestatud research-andmetele.</p>{error && <p>{error}. Käivita eraldi terminalis <code>npm run research:api</code>.</p>}<h2>Auto24 import</h2><p>Kleebi kuulutuse link. Kui Auto24 turvakontroll ei luba lehte lugeda, täida tuvastatud andmed käsitsi ja lisa auto järjekorda.</p><input value={url} onChange={(event) => setUrl(event.target.value)} placeholder="https://www.auto24.ee/soidukid/..." /><button onClick={inspect}>Kontrolli linki</button>{inspectMessage && <p>{inspectMessage}</p>}<div>{(Object.keys(emptyVehicle) as Array<keyof VehicleForm>).map((field) => <input key={field} value={vehicle[field]} onChange={(event) => setVehicle({ ...vehicle, [field]: event.target.value })} placeholder={field} />)}</div><button onClick={queue}>Lisa research-järjekorda</button>{activeVehicle ? <h2>Leitud probleemid: {activeVehicle.make} {activeVehicle.model} {activeVehicle.variant} ({claims.length})</h2> : <h2>Leitud probleemid</h2>}{!activeVehicle ? <p>Vali või lisa kõigepealt auto, siis näitan ainult selle auto claime.</p> : claims.length === 0 ? <p>Selle auto kohta ei ole veel claime salvestatud.</p> : <div>{claims.map((claim) => <article key={claim.id}><h3>{claim.make} {claim.model} {claim.variant ?? ''}: {claim.issue}</h3><p><strong>Komponent:</strong> {claim.component}</p><p><strong>Sümptomid:</strong> {claim.symptoms.join(', ')}</p><p><strong>Parandus:</strong> {claim.repair ?? '—'}</p><p><strong>Tõend:</strong> {claim.evidence_level} · confidence {claim.confidence} · allikaid {claim.source_count} · {claim.language}</p></article>)}</div>}<h2>Research-jobs ({jobs.length})</h2><ul>{jobs.map((job) => <li key={job.id}>{job.make} {job.model} — {job.status}{job.error ? ` — ${job.error}` : ''}</li>)}</ul></div></main>;
}
export default ResearchDebug;
