export const researchApi = (import.meta.env.VITE_RESEARCH_API_URL ?? 'http://127.0.0.1:8787/api').replace(/\/$/, '');
export interface ListingSnapshot { url: string; vin?: string | null; registrationNumber?: string | null; listingId?: string | null; title?: string | null; make: string; model: string; generation?: string | null; variant?: string | null; engine?: string | null; engineCode?: string | null; transmission?: string | null; year?: number | null; mileageKm?: number | null; priceEur?: number | null; location?: string | null; }
export interface Claim { id: string; component: string; issue: string; symptoms: string[]; affected_years: number[]; mileage_min_km: number | null; mileage_max_km: number | null; repair: string | null; cost_min_eur: number | null; cost_max_eur: number | null; evidence_level: string; confidence: number; source_count: number; language: string; sources: Array<{ title: string | null; url: string }>; }
export interface Analysis extends ListingSnapshot { id: string; status: 'researching' | 'completed' | 'needs_review' | 'failed'; researchJobId?: string | null; error?: string | null; createdAt: string; claims: Claim[]; }
export interface VinImageResult { url: string; title: string; query: string; searchUrl: string; }
export const getClientId = (): string => { const key = 'autotark_client_id'; const existing = window.localStorage.getItem(key); if (existing && /^[a-zA-Z0-9_-]{16,100}$/.test(existing)) return existing; const value = typeof crypto.randomUUID === 'function' ? crypto.randomUUID().replace(/-/g, '') : `${Date.now()}${Math.random().toString(36).slice(2)}`; window.localStorage.setItem(key, value); return value; };
const request = async <T>(path: string, init?: RequestInit): Promise<T> => { const response = await fetch(`${researchApi}${path}`, { ...init, headers: { 'content-type': 'application/json', 'x-client-id': getClientId(), ...(init?.headers ?? {}) } }); const body = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(body.error ?? 'Päring ebaõnnestus'); return body; };
export const inspectAuto24 = (url: string) => request<{ status: 'parsed' | 'needs_manual'; url: string; vehicle: ListingSnapshot; message?: string }>('/auto24/inspect', { method: 'POST', body: JSON.stringify({ url }) });
export const createAnalysis = (listing: ListingSnapshot) => request<{ id: string }>('/analyses', { method: 'POST', body: JSON.stringify({ listing }) });
export const getAnalysis = (id: string) => request<Analysis>(`/analyses/${encodeURIComponent(id)}`);
export const getVinImages = (id: string) => request<{ vin: string | null; images: VinImageResult[]; googleSearchUrl: string | null }>(`/analyses/${encodeURIComponent(id)}/images`).then((result) => ({ ...result, images: result.images.map((image) => ({ ...image, url: `${researchApi}/image-proxy?url=${encodeURIComponent(image.url)}` })) }));
export interface SavedCar extends ListingSnapshot { id: string; analysisId?: string | null; createdAt: string; }
export const getSavedCars = () => request<SavedCar[]>('/saved-cars');
export const saveCar = (car: ListingSnapshot, analysisId?: string | null) => request<{ id: string }>('/saved-cars', { method: 'POST', body: JSON.stringify({ car, analysisId }) });
export const deleteSavedCar = (id: string) => request<{ ok: true }>(`/saved-cars/${encodeURIComponent(id)}`, { method: 'DELETE' });
export const getComparison = () => request<SavedCar[]>('/comparison');
export const updateComparison = (carIds: string[]) => request<{ ok: true }>('/comparison', { method: 'PUT', body: JSON.stringify({ carIds }) });
